- prob: 0.05
  types:
  - 构图.制图特效
  - 构图.图片类型
  - 构图.画风
- prob: 0.07
  types:
  - 构图.色彩
- prob: 0.1
  types:
  - 构图.视角
- prob: 0.07
  types:
  - 构图.背景
- prob: 0.4
  types:
  - 人文景观.位置.室内
  - 人文景观.位置.室外
  - 人文景观.位置.建筑物
  - 人文景观.城市
- prob: 0.4
  types:
  - 自然景观.位置.室外
  - 自然景观.天空/气象
  - 自然景观.花卉
- prob: 0.12
  types:
  - 人物.摆位
- prob: 0.05
  types:
  - 人物.类型
- prob: 0.7
  types:
  - 人物.胸部size
- prob: 0.5
  types:
  - 人物.衣装
- prob: 0.24
  types:
  - 人物.全身装饰
- prob: 0.24
  types:
  - 人物.上身装饰
- prob: 0.15
  types:
  - 人物.下身装饰
- prob: 0.3
  types:
  - 人物.鞋袜
- prob: 0.2
  types:
  - 人物.胸部
- prob: 0.2
  types:
  - 人物.头发
- prob: 0.3
  types:
  - 人物.头部饰品
- prob: 0.1
  types:
  - 人物.耳朵
- prob: 0.11
  types:
  - 人物.脖子
- prob: 0.15
  types:
  - 人物.动作
- prob: 0.15
  types:
  - 人物.面部
- prob: 0.2
  types:
  - 物品
- prob: 0.1
  types:
  - 人文景观.食物.主食
  - 人文景观.食物.乳制品
  - 人文景观.食物.水果
  - 人文景观.食物.糖果零食
  - 人文景观.食物.肉类与海鲜
  - 人文景观.食物.蔬菜与香料
  - 人文景观.食物.调味料
  - 人文景观.食物.谷制品
  - 人文景观.食物.饮料
